package ru.stvort.handlers;

/**
 * Registry of command line commands metadata,
 * that can be generated by {@link ru.stvort.handlers.CliCommandHandlersRegistrationPostProcessor}
 * for methods annotated with {@link ru.stvort.annotations.CliCommandMapping}.
 *
 * @author Alexander Orudzhev
 *
 * @see ru.stvort.annotations.CliCommandMapping
 * @see ru.stvort.handlers.CliCommandHandlersRegistrationPostProcessor
 */
public interface CliCommandHandlersRegistry {
    /**
     * @param metaData - command line commands metadata to register
     * @see ru.stvort.handlers.CliCommandMetaData
     */
    void registerCommand(CliCommandMetaData metaData);
}
